version: '3.1'
services:
  wordpress:
    build:
      context: .
      dockerfile: wp/Dockerfile
      args:
        uid: ${UID}
    container_name: ${APP_NAME:-wp}_app
    ports:
      - '${APP_PORT:-8000}:80'
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: '${DB_USERNAME}'
      WORDPRESS_DB_PASSWORD: '${DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${DB_DATABASE}'
    volumes:
      - ../wordpress:/var/www/html
    networks:
      - wp-network
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME:-wp}_mysql
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=2213
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s
    networks:
      - wp-network
networks:
  wp-network:
    driver: bridge
